import {useEffect,useState} from "react";
import s from "../../RetailWorkspace.module.css";
import {uploadProductImage} from "../../../api/commerceApi";
import {Modal,Field,Empty,Metric,Panel,Toolbar,filteredRows,PaymentHistory,RETAIL_CATEGORIES,today} from "./shared";
import {ConfirmModal} from "./modals";
function Products({items,query,setQuery,onAdd,onEdit,onDelete,money}){const [archiveTarget,setArchiveTarget]=useState(null);const archive=async()=>{if(!archiveTarget)return;try{await onDelete(archiveTarget)}finally{setArchiveTarget(null)}};return <><div className={s.productsToolbar}><div><h2>Product catalogue</h2><p>Create and manage the products customers can buy.</p></div><div className={s.productsToolbarControls}><div className={s.productsSearch}><span aria-hidden="true">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products..." aria-label="Search products"/>{query&&<button type="button" onClick={()=>setQuery("")} aria-label="Clear search">×</button>}</div><button className={s.primary} onClick={onAdd}>＋ Add Product</button></div></div><Panel title={`${items.length} products`} sub="Selling prices are customer-facing. Cost information stays inside the business workspace."><div className={s.tableWrap}><table><thead><tr><th>Product</th><th>Category</th><th>SKU</th><th>Price</th><th>Stock</th><th>Status</th><th/></tr></thead><tbody>{items.map(p=><tr key={p.id}><td><b>{p.name}</b><small>{p.brand||'No brand'}</small></td><td>{p.category||'Uncategorised'}</td><td>{p.sku||'—'}</td><td>{money(p.price)}</td><td>{p.trackInventory?`${p.stockQuantity} ${p.unit||'units'}`:'Not tracked'}</td><td><span className={s.badge}>{p.status}</span></td><td><button className={s.textBtn} onClick={()=>onEdit(p)}>Edit</button><button className={s.textDanger} onClick={()=>setArchiveTarget(p)}>Archive</button></td></tr>)}</tbody></table>{!items.length&&<Empty title="No products yet" text="Build your catalogue and start selling from the POS." action={<button className={s.primary} onClick={onAdd}>Add your first product</button>}/>}</div></Panel>{archiveTarget&&<ConfirmModal title="Archive product" eyebrow="ARCHIVE PRODUCT" confirmLabel="Archive product" onClose={()=>setArchiveTarget(null)} onConfirm={archive}><p>Archive <strong>{archiveTarget.name}</strong>? The product will no longer appear as an active product.</p></ConfirmModal>}</>}
function Customers({items,onAdd,onEdit,onDelete}){return <><Toolbar title="Customers" sub="Business-specific customer relationships, kept isolated to this business." action={<button className={s.primary} onClick={onAdd}>＋ Add Customer</button>}/><Panel title={`${items.length} customers`} sub="Customer identities are global, while this business relationship remains private."><div className={s.customerGrid}>{items.map(c=><div className={s.customer} key={c.membershipId}><div className={s.avatar}>{(c.firstName||'?').slice(0,1)}</div><div><b>{c.firstName||'Customer'} {c.lastName||''}</b><small>{c.phone||'No phone'}</small><small>{c.email||'No email'}</small></div><div><button className={s.textButton} onClick={()=>onEdit(c)}>Edit</button><button className={s.textDanger} onClick={()=>onDelete(c.membershipId)}>Remove</button></div></div>)}</div>{!items.length&&<Empty title="No customers yet" text="Add customers manually or let storefront interactions establish their business relationship." action={<button className={s.primary} onClick={onAdd}>Add customer</button>}/>}</Panel></>}
function Expenses({items,onAdd,onEdit,onDelete,money}){return <><Toolbar title="Expenses" sub="Record operating costs separately from owner withdrawals." action={<button className={s.primary} onClick={onAdd}>＋ Add Expense</button>}/><Panel title="Expense ledger" sub="Rent, salaries, utilities, marketing, repairs and other operating costs."><div className={s.tableWrap}><table><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Amount</th><th>Type</th><th/></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.expenseDate}</td><td><span className={s.badge}>{x.category}</span></td><td>{x.description||'—'}</td><td>{money(x.amount)}</td><td>{x.ownerWithdrawal?'Owner withdrawal':x.recurring?'Recurring':'Operating'}</td><td><button className={s.textButton} onClick={()=>onEdit(x)}>Edit</button><button className={s.textDanger} onClick={()=>onDelete(x.id)}>Delete</button></td></tr>)}</tbody></table>{!items.length&&<Empty title="No expenses yet" text="Record your first operating expense to start tracking business costs." action={<button className={s.primary} onClick={onAdd}>Add expense</button>}/>}</div></Panel></>}

export {Products,Customers,Expenses};
