import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { getCreditsDashboard, initializeCreditPurchase, verifyCreditPurchase, acceptCreditAgreement } from "../api/creditsApi";
import { payWithPaystack } from "../api/subscriptionApi";
import styles from "./EhralCredits.module.css";

const AMOUNTS = [1000, 2500, 5000, 10000];
const money = (n) => `₦${Number(n || 0).toLocaleString("en-NG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const label = (code = "") => code.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, x => x.toUpperCase());

export default function EhralCredits() {
  const navigate = useNavigate();
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [selected, setSelected] = useState(5000); const [custom, setCustom] = useState(""); const [buyOpen, setBuyOpen] = useState(false); const [agreementOpen, setAgreementOpen] = useState(false); const [processing, setProcessing] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); try { setData(await getCreditsDashboard()); setError(""); } catch (e) { setError(e?.response?.data?.message || "We couldn't load your Ehral Credits right now."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const amount = Number(custom || selected); const promo = data?.firstPurchasePromotionEligible ? amount * Number(data?.firstPurchasePromotionMultiplier || 0) : 0;
  const services = data?.services || [];
  const usageText = useMemo(() => { const total = Number(data?.availableCredits || 0); const first = services[0]; if (!first || !Number(first.amount)) return "We'll estimate your service capacity after more activity."; return `At the current ${label(first.billingModel).toLowerCase()} price for ${label(first.serviceCode)}, your balance represents about ${Math.floor(total / Number(first.amount)).toLocaleString()} uses of that service.`; }, [data, services]);
  const purchase = async () => { if (!data?.agreementAccepted) { setBuyOpen(false); setAgreementOpen(true); return; } if (!amount || amount < 1) { setMessage("Enter a valid amount."); return; } setProcessing(true); try { const init = await initializeCreditPurchase(amount); await payWithPaystack({ email: init.email, amountNaira: Number(init.amount), reference: init.reference, publicKey: init.publicKey, onSuccess: async (ref) => { try { await verifyCreditPurchase(ref); setMessage("Your Ehral Credits have been added successfully."); setBuyOpen(false); await load(); } catch (e) { setMessage(e?.response?.data?.message || "Payment was received, but verification is still pending. Please refresh shortly."); } finally { setProcessing(false); } }, onClose: () => setProcessing(false) }); } catch (e) { setMessage(e?.response?.data?.message || e?.message || "We couldn't start the payment."); setProcessing(false); } };
  if (loading) return <div className={styles.page}><div className={styles.skeletonHero}/><div className={styles.loadingLine}>Loading your Ehral Credits…</div></div>;
  return <div className={styles.page}>
    <div className={styles.topRow}><div><button className={styles.back} onClick={() => navigate("/dashboard")}><i className="ti ti-arrow-left"/> Dashboard</button><p className={styles.eyebrow}>EHRAL CREDITS</p><h1>{data?.businessTypeLabel || "Business"} Credits</h1><p className={styles.subtitle}>Power your business with Ehral services.</p></div><button className={styles.buyTop} onClick={() => setBuyOpen(true)}><i className="ti ti-plus"/> Add Credits</button></div>
    {error && <div className={styles.error}>{error}<button onClick={load}>Retry</button></div>}
    {message && <div className={styles.notice} role="status"><span>{message}</span><button onClick={() => setMessage("")} aria-label="Dismiss"><i className="ti ti-x"/></button></div>}
    <section className={styles.hero}>
      <div className={styles.heroGlow}/><div className={styles.heroContent}><div className={styles.heroLabel}><span className={styles.liveDot}/> Available Ehral Credits</div><div className={styles.balance}>{money(data?.availableCredits)}</div><p>Available to access eligible Ehral services for this business.</p><div className={styles.heroActions}><button className={styles.primary} onClick={() => setBuyOpen(true)}><i className="ti ti-wallet"/> Buy Credits</button><button className={styles.secondary} onClick={() => document.getElementById("creditActivity")?.scrollIntoView({behavior:"smooth"})}>View activity</button></div></div>
      <div className={styles.breakdown}><div><span>Purchased</span><strong>{money(data?.purchasedCredits)}</strong><small>Never expires</small></div><div><span>Promotional</span><strong>{money(data?.promotionalCredits)}</strong><small>{data?.promotionalExpiresAt ? `Expires ${new Date(data.promotionalExpiresAt).toLocaleDateString()}` : "Use promotional credits first"}</small></div></div>
    </section>
    <section className={styles.grid2}><article className={styles.card}><div className={styles.cardHead}><div><span className={styles.kicker}>CREDIT HEALTH</span><h2>{Number(data?.availableCredits || 0) > 1000 ? "Healthy" : Number(data?.availableCredits || 0) > 0 ? "Running low" : "Add credits"}</h2></div><div className={styles.healthIcon}><i className="ti ti-bolt"/></div></div><p>{usageText}</p><div className={styles.progress}><span style={{width:`${Math.min(100, Math.max(4, Number(data?.availableCredits || 0) / 100))}%`}}/></div></article><article className={styles.card}><div className={styles.cardHead}><div><span className={styles.kicker}>YOUR BUSINESS</span><h2>{data?.businessTypeLabel || "Ehral Business"}</h2></div><div className={styles.typeIcon}><i className="ti ti-building-store"/></div></div><p>This Credits experience is tailored to the services available to your business type.</p><button className={styles.textButton} onClick={() => setAgreementOpen(true)}>View Credits terms <i className="ti ti-arrow-up-right"/></button></article></section>
    <section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.kicker}>YOUR EHRAL SERVICES</span><h2>Services that use Credits</h2></div><span className={styles.sectionHint}>{services.length} configured</span></div><div className={styles.serviceGrid}>{services.map((s)=><article className={styles.serviceCard} key={s.serviceCode}><div className={styles.serviceIcon}><i className="ti ti-sparkles"/></div><div className={styles.serviceMain}><h3>{label(s.serviceCode)}</h3><p>{label(s.billingModel)} · {money(s.amount)} {s.currency === "NGN" ? "credits" : s.currency}</p></div><span className={styles.serviceArrow}><i className="ti ti-chevron-right"/></span></article>)}</div></section>
    <section className={styles.section} id="creditActivity"><div className={styles.sectionHead}><div><span className={styles.kicker}>CREDIT ACTIVITY</span><h2>Recent activity</h2></div></div><div className={styles.activity}>{(data?.activity || []).length ? data.activity.map(a=><div className={styles.activityRow} key={a.id}><div className={`${styles.activityIcon} ${Number(a.amount)>=0 ? styles.plus : styles.minus}`}><i className={Number(a.amount)>=0 ? "ti ti-arrow-down-left" : "ti ti-arrow-up-right"}/></div><div className={styles.activityInfo}><strong>{a.description || label(a.eventType)}</strong><span>{a.createdAt ? new Date(a.createdAt).toLocaleString() : ""}{a.serviceCode ? ` · ${label(a.serviceCode)}` : ""}</span></div><div className={`${styles.activityAmount} ${Number(a.amount)>=0 ? styles.positive : ""}`}>{Number(a.eventType === "SERVICE_USAGE" ? -Number(a.amount) : Number(a.amount)) < 0 ? "-" : "+"}{money(Math.abs(Number(a.amount || 0)))}</div></div>) : <div className={styles.empty}><i className="ti ti-receipt"/><h3>No credit activity yet</h3><p>Your purchases and Ehral service usage will appear here.</p></div>}</div></section>
    {buyOpen && <div className={styles.overlay} onClick={() => !processing && setBuyOpen(false)}><div className={styles.sheet} onClick={e=>e.stopPropagation()}><button className={styles.close} disabled={processing} onClick={()=>setBuyOpen(false)} aria-label="Close"><i className="ti ti-x"/></button><span className={styles.kicker}>ADD EHRAL CREDITS</span><h2>Power your next Ehral services</h2><p className={styles.sheetSub}>Choose how much to add. Eligible first-purchase promotions are shown before payment.</p><div className={styles.amountGrid}>{AMOUNTS.map(a=><button key={a} className={amount===a&&!custom?styles.amountActive:styles.amount} onClick={()=>{setSelected(a);setCustom("")}}>{money(a)}{a===5000&&<small>Popular</small>}</button>)}</div><div className={styles.customWrap}><span>Custom amount</span><div><b>₦</b><input inputMode="decimal" value={custom} onChange={e=>setCustom(e.target.value.replace(/[^0-9.]/g,""))} placeholder="Enter amount"/></div></div><div className={styles.purchaseSummary}><div><span>Purchased credits</span><strong>{money(amount)}</strong></div><div><span>Promotional credits</span><strong>+{money(promo)}</strong></div><div className={styles.total}><span>Total after payment</span><strong>{money(Number(data?.availableCredits||0)+amount+promo)}</strong></div></div><button className={styles.payButton} disabled={processing||!amount} onClick={purchase}>{processing?<><i className="ti ti-loader-2"/> Processing…</>:<>Continue to secure payment <i className="ti ti-arrow-right"/></>}</button><p className={styles.termsMini}>Purchased credits do not expire and are not refundable or transferable. Promotional credits follow the applicable promotion terms.</p></div></div>}
    {agreementOpen && <div className={styles.overlay} onClick={()=>setAgreementOpen(false)}><div className={styles.sheet} onClick={e=>e.stopPropagation()}><button className={styles.close} onClick={()=>setAgreementOpen(false)} aria-label="Close"><i className="ti ti-x"/></button><span className={styles.kicker}>EHRAL CREDITS TERMS</span><h2>How your Credits work</h2><p className={styles.sheetSub}>Ehral Credits are prepaid service credits used only for eligible Ehral services.</p><div className={styles.termsList}><div><i className="ti ti-check"/><span>Purchased credits do not expire.</span></div><div><i className="ti ti-check"/><span>Purchased credits are not refundable or transferable between businesses.</span></div><div><i className="ti ti-check"/><span>Promotional credits may have an expiration date and additional promotion terms.</span></div><div><i className="ti ti-check"/><span>Ehral uses eligible promotional credits before purchased credits.</span></div><div><i className="ti ti-check"/><span>Service prices are shown through the current Ehral billing configuration.</span></div></div><button className={styles.payButton} onClick={async()=>{try{await acceptCreditAgreement();setAgreementOpen(false);await load();setBuyOpen(true)}catch(e){setMessage(e?.response?.data?.message||"We could not record your agreement.")}}}>I agree and continue</button></div></div>}
  </div>;
}
